name: "Daily: Integration Noble lxd_vm"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 23 * * *'

jobs:
  noble-lxd_vm:
    uses: ./.github/workflows/_integration_common.yml
    with:
      release: noble
      platform: lxd_vm
