name: "Daily: Integration Noble lxd_container"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 22 * * *'

jobs:
  noble-lxd_container:
    uses: ./.github/workflows/_integration_common.yml
    with:
      release: noble
      platform: lxd_container
