name: "Daily: Integration Questing lxd_vm"

on:
  workflow_dispatch:
  schedule:
    - cron: '2 23 * * *'

jobs:
  questing-lxd_vm:
    uses: ./.github/workflows/_integration_common.yml
    with:
      release: questing
      platform: lxd_vm
