name: "Daily: Integration Questing EC2"

on:
  workflow_dispatch:
  schedule:
    # Run Mon & Thurs under reduced frequency for high-cost test runs
    - cron: '2 22 * * 1,4'

jobs:
  questing-ec2:
    uses: ./.github/workflows/_integration_common.yml
    with:
      release: questing
      platform: ec2
