name: "Weekly: Static analysis Tiobe TICS"

# https://library.canonical.com/corporate-policies/information-security-policies/ssdlc/ssdlc---static-code-analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5 * * 6'  # Run at 5:17a (arbitrary) on Saturday UTC

concurrency:
  group: cloudinit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    runs-on: [self-hosted, linux, amd64, tiobe, noble]
    steps:
      - name: Checkout the project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -qy install tox
      - name: Generate coverage report
        run: |
          tox -e py3 -- tests/unittests/ --cov-report=xml:.cover/coverage.xml --color=yes
          # Export tox venv python for TICS to use tox python dependencies.
          source .tox/py3/bin/activate
          echo PATH=$PATH  >> $GITHUB_ENV

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@768de18bedf164ee461bc9ef5e2f2fa1a20b122a  # v3.7
        with:
          mode: qserver
          project: cloud-init
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
